name       : qqc2-desktop-style
version    : 5.72.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/qqc2-desktop-style-5.72.0.tar.xz : 606f92cd5f95d21dcfe2fc546e3046ab3c2e286fc1f8b8374110c8554ace0666
homepage   : https://community.kde.org/Frameworks
license    : GPL-2.0-or-later
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
