name       : qqc2-desktop-style
version    : 5.82.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/qqc2-desktop-style-5.82.0.tar.xz : 3426b476ed3a9de868f31311309b98b2c6535250ea071abc85df7170a42f50ea
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : desktop.theme
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
