name       : qqc2-desktop-style
version    : 5.62.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/qqc2-desktop-style-5.62.0.tar.xz : 97234e956a7fc09bef0665e9a759d6f370419bd3cd2bbbd700849e4cbe549bfa
license    : GPL-2.0-or-later
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
