name       : qqc2-desktop-style
version    : 5.69.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/qqc2-desktop-style-5.69.0.tar.xz : be70ed78ec4b82d96ce6fb573478a18042d14c46fb462bc571dc9b777cf63eb9
homepage   : https://community.kde.org/Frameworks
license    : GPL-2.0-or-later
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
