name       : qqc2-desktop-style
version    : 5.53.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/qqc2-desktop-style-5.53.0.tar.xz : 04d4ed66dd50d0221a04011da8d01376cfbf6b4306760414d0c57e8eeb7027b8
license    : GPL-2.0-or-later
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwidgetsaddons-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
