name       : qqc2-desktop-style
version    : 5.77.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/qqc2-desktop-style-5.77.0.tar.xz : bb9736691e19ec72138035f46cb7e1d760b07ee9f8946c421c3b611c3ffe028d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
