name       : qqc2-desktop-style
version    : 5.89.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/qqc2-desktop-style-5.89.0.tar.xz : ac5089295a0affd0e0abef737265b318b2ab3ad888df45b56a74b86416045ee0
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : desktop.theme
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
