name       : qqc2-desktop-style
version    : 5.80.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/qqc2-desktop-style-5.80.0.tar.xz : efb3ed865996100921b8dd7340d4f7dd1bc477381ce401cf36b8ed548d3dbe91
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : desktop.theme
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
