name       : qqc2-desktop-style
version    : 5.40.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/qqc2-desktop-style-5.40.0.tar.xz : 89ec1b98a3b9491f37cd3c13ff6ec047d773efb0fb697c14b9a8388fb0b6ed4a
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwidgetsaddons-devel
    - plasma-integration
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    cd $installdir; qml_cache
