name       : qqc2-desktop-style
version    : 5.52.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/qqc2-desktop-style-5.52.0.tar.xz : 2ee8a3b3a50b2d8a71e097dd9f687ace823dca05acb30595b9bb88cb473b10b7
license    : GPL-2.0-or-later
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwidgetsaddons-devel
    - plasma-integration
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
