name       : qqc2-desktop-style
version    : 5.42.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/qqc2-desktop-style-5.42.0.tar.xz : d3f2f2d2faab02724800186cd0e90fe1dc60e9935f1ee4de0d413ba8197434ab
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwidgetsaddons-devel
    - plasma-integration
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    cd $installdir; qml_cache
