name       : qqc2-desktop-style
version    : 5.39.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.39/qqc2-desktop-style-5.39.0.tar.xz : fb8818b22dbc1f47c38bef488543f025ec5da810e84f5ed732b08969338411e1
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : QtQuickControls 2 style that integrates with the desktop
description: |
    This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher deree of consistency between QWidget-based and QML-based apps.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwidgetsaddons-devel
    - plasma-integration
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    cd $installdir; qml_cache
